"""JSON Schema and compact RST renderers driven only by Pydantic metadata."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from pydantic import BaseModel
from pydantic_core import PydanticUndefined

from .models import (
    INPUT_MODELS,
    OUTPUT_MODELS,
    STEP_MODELS,
    FileDestination,
    InternalSequenceReference,
    Recipe,
    RecipeHeader,
    Sequence,
    UploadFile,
)

ROOT = Path(__file__).parent
SCHEMA_PATH = ROOT / "recipe.schema.json"
REFERENCE_PATH = ROOT / "recipe_reference.rst"


def render_json_schema() -> str:
    """Render deterministic JSON Schema for the aggregate typed model."""
    schema = Recipe.model_json_schema(by_alias=True, mode="validation")
    schema["$comment"] = (
        "SPDX-FileCopyrightText: 2026 CERN <home.cern>; "
        "SPDX-License-Identifier: LGPL-2.1-or-later"
    )
    return json.dumps(
        schema,
        indent=2,
        sort_keys=True,
    ) + "\n"


def _annotation_name(annotation: Any) -> str:
    text = str(annotation).replace("typing.", "")
    text = text.replace("<class '", "").replace("'>", "")
    text = re.sub(r"(?:[\w.]*recipe_pydantic\.models|__main__)\.", "", text)
    return text.replace("NoneType", "None")


def _example(field: Any) -> Any:
    if field.examples:
        return field.examples[0]
    if field.default is not PydanticUndefined:
        return field.default
    return PydanticUndefined


def _model_block(model: type[BaseModel], anchor: str) -> list[str]:
    title = model.__name__
    lines = [f".. _{anchor}:", "", title, "~" * len(title), ""]
    description = (model.__doc__ or "").strip()
    if description:
        lines.extend([description, ""])
    lines.extend([".. list-table:: Fields", "   :header-rows: 1", "", "   * - Field", "     - Type", "     - Required/default", "     - Description / example"])
    for name, field in model.model_fields.items():
        public_name = field.alias or name
        default = "required" if field.is_required() else f"default ``{field.default!r}``"
        example = _example(field)
        detail = field.description or ""
        if example is not PydanticUndefined:
            detail += f" Example: ``{example!r}``."
        lines.extend([
            f"   * - ``{public_name}``",
            f"     - ``{_annotation_name(field.annotation)}``",
            f"     - {default}",
            f"     - {detail}",
        ])
    lines.append("")
    return lines


def render_reference() -> str:
    """Render the review-oriented recipe reference from model metadata."""
    lines = [
        ".. SPDX-FileCopyrightText: 2026 CERN <home.cern>",
        ".. SPDX-License-Identifier: LGPL-2.1-or-later",
        ".. This file is generated by the Pydantic recipe spike.",
        "",
        "Pydantic Recipe Language 2.0.0",
        "================================",
        "",
        "This candidate reference is generated directly from strict, frozen Pydantic models.",
        "",
        "Documents",
        "---------",
        "",
    ]
    lines.extend(_model_block(RecipeHeader, "recipe-header"))
    lines.extend(_model_block(Sequence, "recipe-sequence"))

    lines.extend(["Nested structures", "-----------------", ""])
    for model in (InternalSequenceReference, FileDestination, UploadFile):
        lines.extend(_model_block(model, f"recipe-structure-{model.__name__.lower()}"))

    lines.extend(["Authorable steps", "----------------", ""])
    for model in STEP_MODELS:
        lines.extend(_model_block(model, f"recipe-step-{model.__name__.lower()}"))

    lines.extend(["Input mappings", "--------------", ""])
    for model in INPUT_MODELS:
        kind = model.model_fields["type"].examples[0]
        lines.extend(_model_block(model, f"recipe-input-{kind}"))

    lines.extend(["Output mappings", "---------------", ""])
    for model in OUTPUT_MODELS:
        kind = model.model_fields["type"].examples[0]
        lines.extend(_model_block(model, f"recipe-output-{kind}"))
    return "\n".join(lines).rstrip() + "\n"


def write_artifacts() -> None:
    SCHEMA_PATH.write_text(render_json_schema(), encoding="utf-8")
    REFERENCE_PATH.write_text(render_reference(), encoding="utf-8")


if __name__ == "__main__":
    write_artifacts()
